packages:
  - apps/*
  - native/*
  - packages/*
engineStrict: true
linkWorkspacePackages: false
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': false
  electron: true
  electron-winstaller: false
  koffi: true
  node-pty: true
  protobufjs: false
