#import "pasteboard.h"
#import <ApplicationServices/ApplicationServices.h>
#import <CoreGraphics/CoreGraphics.h>

// 剪贴板操作标记和大小上限必须与 TypeScript Core 契约保持一致。
static NSString *const HCOperationType = @"io.github.pgw10086.hermit.smart-clipboard.operation-id";
static NSString *const HCSourceType = @"org.nspasteboard.source";
static NSUInteger const HCMaxTextBytes = 2 * 1024 * 1024;
static NSUInteger const HCMaxImageBytes = 20 * 1024 * 1024;
static NSUInteger const HCMaxDecodeBytes = 128 * 1024 * 1024;
static NSUInteger const HCMaxImagePixels = 32 * 1024 * 1024;
static NSUInteger const HCMaxFileItems = 256;
static NSUInteger const HCMaxFileManifestBytes = 1024 * 1024;

// 读取期间 pasteboard changeCount 变化时返回可重试的并发结果。
static NSDictionary *HCUnstable(NSInteger before, NSInteger after) {
  return @{ @"status": @"unstable", @"beforeGeneration": @(before), @"afterGeneration": @(after) };
}

// 统一把 nil pasteboardItems 解释为空数组，后续解析只处理真实项目。
static NSArray<NSPasteboardItem *> *HCItems(NSPasteboard *pasteboard) {
  return pasteboard.pasteboardItems ?: @[];
}

// 汇总并去重所有 pasteboard type，供优先级解析和诊断使用。
static NSArray<NSString *> *HCTypes(NSArray<NSPasteboardItem *> *items) {
  NSMutableOrderedSet<NSString *> *types = [NSMutableOrderedSet orderedSet];
  for (NSPasteboardItem *item in items) {
    for (NSPasteboardType type in item.types) [types addObject:type];
  }
  return types.array;
}

// 读取指定类型的第一段字符串表示。
static NSString *HCFirstString(NSArray<NSPasteboardItem *> *items, NSString *type) {
  for (NSPasteboardItem *item in items) {
    NSString *value = [item stringForType:type];
    if (value != nil) return value;
  }
  return nil;
}

// 将 NSRunningApplication 收窄为跨进程传输的稳定身份字段。
static NSDictionary *HCAppIdentity(NSRunningApplication *application) {
  if (application == nil) return nil;
  NSMutableDictionary *result = [@{ @"pid": @(application.processIdentifier) } mutableCopy];
  if (application.bundleIdentifier != nil) result[@"bundleIdentifier"] = application.bundleIdentifier;
  if (application.localizedName != nil) result[@"localizedName"] = application.localizedName;
  if (application.launchDate != nil) result[@"launchDateMs"] = @([application.launchDate timeIntervalSince1970] * 1000.0);
  return result;
}

// 捕获当前前台应用；调用方会在发送粘贴前重新校验身份。
NSDictionary *HCCaptureFrontmostApplication(void) {
  return HCAppIdentity(NSWorkspace.sharedWorkspace.frontmostApplication);
}

// 优先使用 pasteboard 明确提供的来源标记，缺失时才采样前台应用。
static NSDictionary *HCSourceApplication(NSArray<NSPasteboardItem *> *items) {
  NSString *explicitSource = HCFirstString(items, HCSourceType);
  if (explicitSource.length > 0) {
    return @{ @"bundleIdentifier": explicitSource, @"basis": @"explicit-marker" };
  }
  NSDictionary *frontmost = HCCaptureFrontmostApplication();
  if (frontmost == nil) return nil;
  NSMutableDictionary *sample = [frontmost mutableCopy];
  sample[@"basis"] = @"frontmost-sample";
  return sample;
}

// 识别 NSPasteboard 约定的临时、隐私和自动生成标记。
static NSArray<NSString *> *HCIgnoreMarkers(NSArray<NSString *> *types) {
  NSArray<NSString *> *known = @[
    @"org.nspasteboard.TransientType",
    @"org.nspasteboard.ConcealedType",
    @"org.nspasteboard.AutoGeneratedType",
  ];
  NSMutableArray<NSString *> *found = [NSMutableArray array];
  for (NSString *marker in known) if ([types containsObject:marker]) [found addObject:marker];
  return found;
}

// 构造文件 URL 快照并在原生层限制项目数和 manifest 大小。
static NSDictionary *HCFileSnapshot(NSArray<NSPasteboardItem *> *items) {
  NSMutableArray<NSString *> *urls = [NSMutableArray array];
  NSUInteger manifestBytes = 0;
  for (NSPasteboardItem *item in items) {
    NSString *value = [item stringForType:NSPasteboardTypeFileURL];
    if (value == nil) continue;
    NSURL *url = [NSURL URLWithString:value];
    if (!url.isFileURL) continue;
    NSString *absolute = url.absoluteString;
    manifestBytes += [absolute lengthOfBytesUsingEncoding:NSUTF8StringEncoding];
    if (urls.count >= HCMaxFileItems || manifestBytes > HCMaxFileManifestBytes) return nil;
    [urls addObject:absolute];
  }
  return urls.count == 0 ? nil : @{ @"kind": @"FILE_LIST", @"fileUrls": urls };
}

// 解码图片并在进入 Node 前限制解码内存、像素数和 PNG 大小。
static NSDictionary *HCImageSnapshot(NSArray<NSPasteboardItem *> *items) {
  for (NSPasteboardItem *item in items) {
    NSData *source = [item dataForType:NSPasteboardTypePNG] ?: [item dataForType:NSPasteboardTypeTIFF];
    if (source == nil) continue;
    if (source.length > HCMaxDecodeBytes) return nil;
    NSImage *image = [[NSImage alloc] initWithData:source];
    if (image == nil) return nil;
    NSRect proposed = NSMakeRect(0, 0, image.size.width, image.size.height);
    CGImageRef decoded = [image CGImageForProposedRect:&proposed context:nil hints:nil];
    if (decoded == nil) return nil;
    NSUInteger width = CGImageGetWidth(decoded);
    NSUInteger height = CGImageGetHeight(decoded);
    if (width == 0 || height == 0 || width > HCMaxImagePixels / height) return nil;
    NSBitmapImageRep *representation = [[NSBitmapImageRep alloc] initWithCGImage:decoded];
    if (representation == nil) continue;
    NSData *png = [representation representationUsingType:NSBitmapImageFileTypePNG properties:@{}];
    if (png == nil || png.length > HCMaxImageBytes) return nil;
    return @{
      @"kind": @"IMAGE",
      @"pngBase64": [png base64EncodedStringWithOptions:0],
      @"width": @(width),
      @"height": @(height),
      @"hasAlpha": @(representation.hasAlpha),
    };
  }
  return nil;
}

// 读取文本及可选 HTML/RTF，并统一执行单项大小限制。
static NSDictionary *HCTextSnapshot(NSArray<NSPasteboardItem *> *items) {
  for (NSPasteboardItem *item in items) {
    NSString *plain = [item stringForType:NSPasteboardTypeString];
    if (plain == nil) continue;
    if ([plain lengthOfBytesUsingEncoding:NSUTF8StringEncoding] > HCMaxTextBytes) return nil;
    NSMutableDictionary *result = [@{ @"kind": @"TEXT", @"plain": plain } mutableCopy];
    NSData *html = [item dataForType:NSPasteboardTypeHTML];
    NSData *rtf = [item dataForType:NSPasteboardTypeRTF];
    if (html.length > HCMaxTextBytes || rtf.length > HCMaxTextBytes) return nil;
    if (html != nil) result[@"htmlBase64"] = [html base64EncodedStringWithOptions:0];
    if (rtf != nil) result[@"rtfBase64"] = [rtf base64EncodedStringWithOptions:0];
    return result;
  }
  return nil;
}

// 先读取 changeCount，再解析并复核 changeCount，确保快照对应同一 generation。
NSDictionary *HCReadStableSnapshot(NSPasteboard *pasteboard, NSNumber *lastGeneration, HCPasteboardTestHook hook) {
  NSInteger current = pasteboard.changeCount;
  if (lastGeneration == nil) return @{ @"status": @"baseline", @"generation": @(current) };
  if (current == lastGeneration.integerValue) return @{ @"status": @"unchanged", @"generation": @(current) };

  NSInteger before = current;
  NSArray<NSPasteboardItem *> *items = HCItems(pasteboard);
  NSArray<NSString *> *types = HCTypes(items);
  NSString *operationId = HCFirstString(items, HCOperationType);
  NSArray<NSString *> *markers = HCIgnoreMarkers(types);
  NSDictionary *snapshot = nil;
  NSString *status = @"snapshot";
  if (markers.count > 0) status = @"ignored";
  else if ([types containsObject:NSPasteboardTypeFileURL]) snapshot = HCFileSnapshot(items);
  else if ([types containsObject:NSPasteboardTypePNG] || [types containsObject:NSPasteboardTypeTIFF]) snapshot = HCImageSnapshot(items);
  else if ([types containsObject:NSPasteboardTypeString]) snapshot = HCTextSnapshot(items);
  if (snapshot == nil && [status isEqualToString:@"snapshot"]) status = @"unsupported";

  if (hook != nil) hook();
  NSInteger after = pasteboard.changeCount;
  if (after != before) return HCUnstable(before, after);

  NSMutableDictionary *result = [@{ @"status": status, @"generation": @(before) } mutableCopy];
  if (operationId != nil) result[@"operationId"] = operationId;
  if ([status isEqualToString:@"ignored"]) result[@"markers"] = markers;
  if ([status isEqualToString:@"unsupported"]) result[@"types"] = types;
  if (snapshot != nil) {
    result[@"snapshot"] = snapshot;
    NSDictionary *source = HCSourceApplication(items);
    if (source != nil) result[@"sourceApp"] = source;
  }
  return result;
}

// 解码 TypeScript 传入的 base64 内容，失败由调用方转换为 write-failed。
static NSData *HCDecodeBase64(NSString *value) {
  return value == nil ? nil : [[NSData alloc] initWithBase64EncodedString:value options:0];
}

// 将统一 payload 构造为 AppKit pasteboard items，并附加操作身份标记。
static NSArray<NSPasteboardItem *> *HCBuildItems(NSDictionary *payload, NSString *operationId) {
  NSString *kind = payload[@"kind"];
  NSMutableArray<NSPasteboardItem *> *items = [NSMutableArray array];
  if ([kind isEqualToString:@"TEXT"]) {
    NSString *plain = payload[@"plain"];
    if (![plain isKindOfClass:NSString.class] || [plain lengthOfBytesUsingEncoding:NSUTF8StringEncoding] > HCMaxTextBytes) return nil;
    NSPasteboardItem *item = [[NSPasteboardItem alloc] init];
    [item setString:plain forType:NSPasteboardTypeString];
    NSData *html = HCDecodeBase64(payload[@"htmlBase64"]);
    NSData *rtf = HCDecodeBase64(payload[@"rtfBase64"]);
    if ((payload[@"htmlBase64"] != nil && html == nil) || (payload[@"rtfBase64"] != nil && rtf == nil)
        || html.length > HCMaxTextBytes || rtf.length > HCMaxTextBytes) return nil;
    if (html != nil) [item setData:html forType:NSPasteboardTypeHTML];
    if (rtf != nil) [item setData:rtf forType:NSPasteboardTypeRTF];
    [items addObject:item];
  } else if ([kind isEqualToString:@"IMAGE"]) {
    NSData *png = HCDecodeBase64(payload[@"pngBase64"]);
    if (png == nil || png.length > HCMaxImageBytes) return nil;
    NSPasteboardItem *item = [[NSPasteboardItem alloc] init];
    [item setData:png forType:NSPasteboardTypePNG];
    [items addObject:item];
  } else if ([kind isEqualToString:@"FILE_LIST"]) {
    NSArray *urls = payload[@"fileUrls"];
    if (![urls isKindOfClass:NSArray.class] || urls.count == 0 || urls.count > HCMaxFileItems) return nil;
    NSUInteger manifestBytes = 0;
    for (id value in urls) {
      if (![value isKindOfClass:NSString.class]) return nil;
      manifestBytes += [value lengthOfBytesUsingEncoding:NSUTF8StringEncoding];
      if (manifestBytes > HCMaxFileManifestBytes) return nil;
      NSURL *url = [NSURL URLWithString:value];
      if (!url.isFileURL) return nil;
      NSPasteboardItem *item = [[NSPasteboardItem alloc] init];
      [item setString:url.absoluteString forType:NSPasteboardTypeFileURL];
      [items addObject:item];
    }
  } else {
    return nil;
  }
  [items.firstObject setString:operationId forType:HCOperationType];
  return items;
}

// 写入后同时校验 changeCount 和 operationId，避免把并发覆盖误判为成功。
NSDictionary *HCWriteSnapshot(NSPasteboard *pasteboard, NSDictionary *payload, NSString *operationId, HCPasteboardTestHook hook) {
  if (operationId.length == 0) return @{ @"status": @"failed", @"reason": @"write-failed" };
  NSArray<NSPasteboardItem *> *items = HCBuildItems(payload, operationId);
  if (items == nil) return @{ @"status": @"failed", @"reason": @"write-failed" };
  NSInteger generation = [pasteboard clearContents];
  BOOL written = [pasteboard writeObjects:items];
  if (hook != nil) hook();
  NSInteger observed = pasteboard.changeCount;
  if (!written) return @{ @"status": @"failed", @"reason": @"write-failed" };
  if (observed != generation) return @{ @"status": @"conflict", @"observedGeneration": @(observed) };
  NSString *writtenOperation = HCFirstString(HCItems(pasteboard), HCOperationType) ?: @"";
  if (![writtenOperation isEqualToString:operationId]) {
    return @{ @"status": @"failed", @"reason": @"marker-verification-failed" };
  }
  return @{ @"status": @"written", @"generation": @(generation) };
}

// 依据 PID、bundle identifier 和启动时间确认目标仍是同一个应用实例。
static NSRunningApplication *HCValidateApplication(NSDictionary *identity, NSString **reason) {
  NSNumber *pid = identity[@"pid"];
  if (![pid isKindOfClass:NSNumber.class]) { *reason = @"target-gone"; return nil; }
  NSRunningApplication *application = [NSRunningApplication runningApplicationWithProcessIdentifier:pid.intValue];
  if (application == nil || application.terminated) { *reason = @"target-gone"; return nil; }
  NSString *bundle = identity[@"bundleIdentifier"];
  if ([bundle isKindOfClass:NSString.class] && ![application.bundleIdentifier isEqualToString:bundle]) {
    *reason = @"target-identity-mismatch"; return nil;
  }
  NSNumber *launchDateMs = identity[@"launchDateMs"];
  if ([launchDateMs isKindOfClass:NSNumber.class] && application.launchDate != nil) {
    double actual = [application.launchDate timeIntervalSince1970] * 1000.0;
    if (fabs(actual - launchDateMs.doubleValue) > 1.0) { *reason = @"target-identity-mismatch"; return nil; }
  }
  return application;
}

// 请求激活已校验的目标应用；系统拒绝时保持 copy-only 语义。
NSDictionary *HCRequestActivate(NSDictionary *identity) {
  NSString *reason = nil;
  NSRunningApplication *target = HCValidateApplication(identity, &reason);
  if (target == nil) return @{ @"status": @"copy-only", @"reason": reason };
  BOOL accepted;
  if (@available(macOS 14.0, *)) {
    [NSApp yieldActivationToApplication:target];
    accepted = [target activateFromApplication:NSRunningApplication.currentApplication options:0];
  } else {
    accepted = [target activateWithOptions:0];
  }
  return accepted ? @{ @"status": @"requested" }
                  : @{ @"status": @"copy-only", @"reason": @"activation-rejected" };
}

// 粘贴前再次确认系统剪贴板仍属于本次写入。
static BOOL HCOperationMatches(NSPasteboard *pasteboard, NSString *operationId, NSInteger generation) {
  NSString *currentOperation = HCFirstString(HCItems(pasteboard), HCOperationType) ?: @"";
  return pasteboard.changeCount == generation && [currentOperation isEqualToString:operationId];
}

// 只有目标仍在前台、权限可用且剪贴板身份未变时才发送 Command+V。
NSDictionary *HCPostPasteIfCurrent(NSPasteboard *pasteboard, NSDictionary *identity, NSString *operationId, NSInteger generation) {
  NSString *reason = nil;
  NSRunningApplication *target = HCValidateApplication(identity, &reason);
  if (target == nil) return @{ @"status": @"copy-only", @"reason": reason };
  if (NSWorkspace.sharedWorkspace.frontmostApplication.processIdentifier != target.processIdentifier) {
    return @{ @"status": @"copy-only", @"reason": @"target-not-frontmost", @"retryable": @YES };
  }
  if (!AXIsProcessTrusted()) return @{ @"status": @"copy-only", @"reason": @"accessibility-denied" };
  if (pasteboard.changeCount != generation) return @{ @"status": @"copy-only", @"reason": @"clipboard-changed" };
  if (!HCOperationMatches(pasteboard, operationId, generation)) {
    return @{ @"status": @"copy-only", @"reason": @"operation-mismatch" };
  }
  CGEventRef down = CGEventCreateKeyboardEvent(NULL, (CGKeyCode)9, true);
  CGEventRef up = CGEventCreateKeyboardEvent(NULL, (CGKeyCode)9, false);
  if (down == NULL || up == NULL) {
    if (down != NULL) CFRelease(down);
    if (up != NULL) CFRelease(up);
    return @{ @"status": @"copy-only", @"reason": @"event-create-failed" };
  }
  CGEventSetFlags(down, kCGEventFlagMaskCommand);
  CGEventSetFlags(up, kCGEventFlagMaskCommand);
  if (NSWorkspace.sharedWorkspace.frontmostApplication.processIdentifier != target.processIdentifier
      || !HCOperationMatches(pasteboard, operationId, generation)) {
    CFRelease(down); CFRelease(up);
    return @{ @"status": @"copy-only", @"reason": @"clipboard-changed" };
  }
  CGEventPost(kCGSessionEventTap, down);
  CGEventPost(kCGSessionEventTap, up);
  CFRelease(down); CFRelease(up);
  return @{
    @"status": @"posted",
    @"clipboardAfter": HCOperationMatches(pasteboard, operationId, generation) ? @"unchanged" : @"changed",
  };
}
